openapi: 3.0.0
info:
  title: ToDo API
  version: 1.0.0
  description: Simple ToDo API

servers:
  - url: http://localhost:3000

paths:
  /api/todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '201':
          description: Created todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /api/todos/{id}:
    put:
      summary: Update a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Updated todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Todo deleted

components:
  schemas:
    Todo:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        done:
          type: boolean
      required:
        - _id
        - title
        - done
    TodoInput:
      type: object
      properties:
        title:
          type: string
        done:
          type: boolean
      required:
        - title